### ISSUE TITLE
Is this project deployed anywhere? How is it licensed?

### ISSUE THREAD

**Issue by hf-kklein** [fabsenet/edi-energy-viewer#1]
Hi @fabsenet,

is this website being deployed to somewhere? 

If no, what are the requirements to do so? Does one need the database filled by fabsenet/edi-energy-extractor?

**Comment by fabsenet** [comment]
I am running this on our company intranet. I do not know of any public running sites, sorry.

**Comment by fabsenet** [comment]
You need a RavenDB instance running. A community edition is enough. You use edi-energy-extractor to produce a copy of the data in your ravendb. finally, edi-energy-viewer connects to your ravendb and displays stuff.

One of the best features is entering a CheckIdenrifier (prüfidentifikator) in the search box and the web site provides a stripped down pdf with only the part of the AHB document describing that checkidentifier.

**Comment by hf-kklein** [comment]
thanks for the info :) maybe I'll look into it a day. How about the license? Could someone re-use the code under open source conditions?

**Comment by fabsenet** [comment]
https://github.com/fabsenet/edi-energy-viewer/blob/master/LICENSE

**Comment by hf-kklein** [comment]
thanks! btw: you could add a github "[topic](https://github.com/topics)" to this repo that it can be found more easily. I'd suggest `ahb`, `bdew` and `anwendungshandbuch`

**Comment by hf-kklein** [comment]
Hey @fabsenet: I just wanted to let you know: We ([Hochfrequenz](https://github.com/Hochfrequenz/)) just open sourced a similar project: [ahb_besser](https://github.com/Hochfrequenz/ahbesser/).
It's also hosted here: https://purple-glacier-0bd2a2403.2.azurestaticapps.net/

Feel free to take a look :)

Our databasis is the [machine_readable-anwendungshandbuecher](https://github.com/Hochfrequenz/machine-readable_anwendungshandbuecher) repo.
